#!/bin/sh

# on Android - Settings - About - About Firefox - tap logo several times; Settings - Advanced - Install extension from file
# about:config xpinstall.signatures.required = false | extensions.langpacks.signatures.required = false
# custom extension collection

set -e

dir=$(dirname "$0")

zip \
  -9r \
  "$dir/nojslite.xpi" \
  "$dir" \
  -x '.git' '*.xpi' 'build'
